[package]
# The current version will come from Cargo.toml

[cargo-release]
# Configuration for cargo-release
pre-release-replacements = [
    { file = "README.md", search = "spiralhouse/aureacore/releases/tag/v[0-9\\.]+", replace = "spiralhouse/aureacore/releases/tag/v{{version}}" },
    { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
    { file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}" },
]
# Configure the tag format
tag-prefix = "v"
# GitHub release configuration
release = true
# Don't publish to crates.io until you're ready
publish = false
# Use conventional commits to determine version bump
# Update version based on conventional commit types:
# - fix: patch bump
# - feat: minor bump
# - BREAKING CHANGE: major bump
conventional-commits = true
