name: Changelog Script Test

on:
  workflow_dispatch:

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        run: |
          echo "Setting up Node.js environment"

      - name: Create test files
        run: |
          # Create a test CHANGELOG.md file
          cat > CHANGELOG.md << 'EOL'
          # Changelog

          All notable changes to AureaCore will be documented in this file.

          The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
          and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

          ## [Unreleased] - ReleaseDate

          ### Added
          - Feature one
          - Feature two

          ### Changed
          - Change one

          ### Fixed
          - Bug fix one

          ## [v0.5.0] - 2023-06-01

          ### Added
          - Initial release
          EOL

          # Display original file
          echo "Original CHANGELOG.md:"
          cat CHANGELOG.md

      - name: Run update-changelog.js script
        run: |
          # Create test changelog content
          CHANGELOG_CONTENT="### Features\n\n* **core:** add new functionality ([abc1234](https://github.com/example/repo/commit/abc1234))\n\n### Bug Fixes\n\n* **api:** fix error handling ([def5678](https://github.com/example/repo/commit/def5678))"

          # Run the script
          node .github/scripts/update-changelog.js "0.6.0" "$CHANGELOG_CONTENT"

          # Display updated file
          echo "Updated CHANGELOG.md:"
          cat CHANGELOG.md
