name: Release Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  check-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      should_release: true
      next_version: "0.1.1"
    steps:
      - uses: actions/checkout@v4

      - name: Mock version detection
        id: check
        run: |
          echo "Current version: 0.1.0"
          echo "Next version would be: 0.1.1"
          echo "should_release=true" >> "$GITHUB_OUTPUT"
          echo "version=0.1.1" >> "$GITHUB_OUTPUT"

  release:
    needs: check-release
    if: ${{ needs.check-release.outputs.should_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mock release process
        run: |
          echo "Creating release version ${{ needs.check-release.outputs.next_version }}"
          echo "Updating CHANGELOG.md"

      - name: Mock GitHub Release creation
        run: |
          echo "Creating GitHub Release v${{ needs.check-release.outputs.next_version }}"
