name: Release Test

on:
  push:
    branches: [main]

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."

      - name: Create test version file
        run: |
          echo '{"version": "0.0.0"}' > test-version.json

      - name: Check conventional commits for release
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "TEST_CHANGELOG.md"
          skip-version-file: false
          skip-on-empty: false
          skip-commit: true
          version-file: "./test-version.json"
          git-branch: ${{ github.ref_name }}
          skip-tag: true

      - name: Display results
        run: |
          echo "Should release? ${{ steps.changelog.outputs.skipped == 'false' }}"
          echo "New version: ${{ steps.changelog.outputs.version }}"
          echo "Changelog contents:"
          cat TEST_CHANGELOG.md

      - name: Debug commit history
        run: |
          echo "Last 10 commits:"
          git log -n 10 --oneline
          echo ""
          echo "Conventional commits since latest tag:"
          git log $(git describe --tags --abbrev=0)..HEAD --oneline
